### ISSUE TITLE
/config/components ?

### ISSUE THREAD

**Issue by wifi75** [dckiller51/bodymiscale#19]
hello the folder /config/components non exist, why?

**Comment by dckiller51** [comment]
If your installation is new or recent you must create it.

**Comment by dckiller51** [comment]
@wifi75 
Hello, have you solved your problem?

If so, can we close this issue?

**Comment by Stooovie** [comment]
Is there a reason to not just put this in custom_components/bodymiscale? This is kinda confusing. Thanks.

**Comment by dckiller51** [comment]
> Is there a reason to not just put this in custom_components/bodymiscale? This is kinda confusing. Thanks.

The program is to be put without customs / components but the yaml configuration in components or directly in config.yaml. To facilitate the organization of my hassio I have a yaml by components

**Comment by Stooovie** [comment]
I got it working properly but it was a bit of a guessing game. Thanks for your work!

**Comment by SmarterHomeLife** [comment]
I'm also having issues with this, I've created the components directory within config and copied the bodymiscale.yaml file but keep getting an error stating;

Error loading /config/configuration.yaml: in "/config/configuration.yaml", line 85, column 14: Unable to read file /config/components/bodymiscale.yaml.

If I put exactly the same bodymiscale details directly into my configuration.yaml file instead of using the !include it works fine.

**Comment by SmarterHomeLife** [comment]
Got it working, silly error on my end.  Thanks for all your work on this great component.
