### ISSUE TITLE
Lanugage not match with Home Assistant

### ISSUE THREAD

**Issue by 5high** [dckiller51/bodymiscale#58]
I have installed HA and Lauguage set to CHS but interface show me all in English.

Is there any way manully setting it to ZH-HANS?

**Comment by Kvasenok** [comment]
I believe this is because this integration doesn't support CHS. Based on the code it only supports English, Portuguese (Brazil), German and French.
I'll elaborate the question: can we help with translation to other languages somehow? Will a simple pull request of a localization file for the specific language be enough?

**Comment by dckiller51** [comment]
> Je pense que c'est parce que cette intégration ne prend pas en charge CHS. Basé sur le code, il ne prend en charge que l'anglais, le portugais (Brésil), l'allemand et le français. Je vais développer la question : pouvons-nous aider à la traduction vers d'autres langues d'une manière ou d'une autre ? Une simple demande d'extraction d'un fichier de localisation pour la langue spécifique suffira-t-elle ?

Yes of course you can. You have to start from the EN file, then you can post here if you want.
Please note there is very little translation in the components, the associated card is no longer provided.

**Comment by dckiller51** [comment]
No return. If needed, please re-apply.
